### ISSUE TITLE
Add option for making equal size leaves

### ISSUE THREAD

**Issue by NSUSpray** [elmotec/circlify#28]
At the moment, the sizes of nodes of the same level are calculated in relation to each other, so with very deep nesting, the sizes of the leaves become too small, which is not always convenient.

![изображение](https://user-images.githubusercontent.com/15806293/216399997-ddce6e88-b3a6-49bc-a571-c9bc7f8e72ce.png)

Please add the ability to fix leaf sizes so that parent node sizes are calculated automatically, proportional to their contents.

![изображение](https://user-images.githubusercontent.com/15806293/216400236-237948db-b99e-44de-b294-de38f5dc6a0a.png)

**Comment by elmotec** [comment]
Ah, yes @NSUSpray, [we waste space with circles](https://github.com/elmotec/circlify#relative-size-of-circles-in-hierachy) so the area of the circles is proportional to the values within a level and a circle which can make the leaf circle much smaller than the value implies if one looks at the picture as a whole. 

It has the advantage to make the problem much easier to solve because it depends only on the parent circle (enclosure) and the values immediately within that circle. 

Determining the size of all the circles globally (across levels) would make things quite a bit more complex, yes? You could propose a PR if I missed something.  Maybe there is an elegant way to solve this.

I feel the right approach is to scale the leaf-level values before one passes them to circlify.  You could even leverage the `id` attribute to show the actual value that you want to represent with something like:

```python
data = [{'id': 'a1 (0.05)', 'datum': 0.1}, {'id': 'a2 (0.05)', 'datum': 0.1}]  # circles scaled by a factor 2.
```

**Comment by elmotec** [comment]
Closing this because I have not plan to implement this feature. Probably easier to adjust the value in input as mentioned last year.
