### ISSUE TITLE
Circlify Funktion

### ISSUE THREAD

**Issue by alexwloa** [elmotec/circlify#29]
I have tried to understand your function in order to determine the original diameter of the outer circle. For example: Input circlify.circlify(1,4), for a given radius of 2.5 you should get for the first circle 1 -> r=0.5 and for the second 4 -> r=2 in the console. Because it should fit exactly into the given radius without scaling. Why is that not the case? 

Code:
```
import matplotlib.pyplot as plt
import circlify

random_numbers_2 = [1,4] # für circlify

target_enclosure = circlify.Circle(x=0, y=0, r=2.5)
# Algoritmus
circles_2= circlify.circlify(random_numbers_2, show_enclosure=True, target_enclosure=target_enclosure)

# Ausgeben
print(circles_2)

circlify.bubbles(circles_2)
```

![image](https://github.com/elmotec/circlify/assets/100837230/d6093a8d-3d8e-45a6-9a5f-917b3c561ffc)

Information: My goal is to find the minimum diameter of the outer circle and the ordering of the different circles.

**Comment by elmotec** [comment]
Hi @alexwloa, thanks for trying out circlify.  The circles are computed so that the input values are proportional to the _area_ of the circles, as opposed to the radius.  In other words, the values are proportional to the _square_ of the radius (area = π x r^2), not proportional to the radius.

The 2 circles fit exactly in a 2.5 radius enclosure but the ratio of the radius between the 2 circles is 1.6666 / 0.8333 = 2 (per your snippet above) which is exactly sqrt(4 / 1) = sqrt(4) = 2.

![image](https://github.com/elmotec/circlify/assets/1107551/2c0715e1-cc93-40e5-9ad1-e287e599d216)

The rationale for that choice is that I wanted the circles to "look" relatively bigger as the value were bigger, I did not want the circles to grow with the square of the values by default. If that's what you want, you can input the square of the value (1, 16) instead of (1, 4) to get circles with radius of exactly 0.5 and 2.

![image](https://github.com/elmotec/circlify/assets/1107551/35cf9a2b-f406-4a9d-b0e5-7b745fe45585)

I hope it's clear but feel free to follow up if not.
